"""empty message

Revision ID: 29b91492b87b
Revises: 760222087138
Create Date: 2026-09-03 10:32:46.244469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29b91492b87b'
down_revision: Union[str, None] = '760222087138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_query',
    sa.Column('value', sa.String(), nullable=False, comment='Строка запроса'),
    sa.Column('results_count', sa.Integer(), nullable=False, comment='Количество найденных материалов по запросу'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время создания'),
    sa.Column('deleted', sa.DateTime(), nullable=True, comment='Время удаления'),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время последнего изменения'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_query_created'), 'search_query', ['created'], unique=False)
    op.create_index(op.f('ix_search_query_deleted'), 'search_query', ['deleted'], unique=False)
    op.create_index(op.f('ix_search_query_modified'), 'search_query', ['modified'], unique=False)
    op.alter_column('file_access_logs', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.alter_column('file_contents', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.alter_column('file_types', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.alter_column('files', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.alter_column('tags', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('files', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('file_types', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('file_contents', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('file_access_logs', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.drop_index(op.f('ix_search_query_modified'), table_name='search_query')
    op.drop_index(op.f('ix_search_query_deleted'), table_name='search_query')
    op.drop_index(op.f('ix_search_query_created'), table_name='search_query')
    op.drop_table('search_query')
    # ### end Alembic commands ###
