"""empty message

Revision ID: 401ab96e8fe8
Revises: 6dea55386a73
Create Date: 2026-01-15 08:15:06.834193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '401ab96e8fe8'
down_revision: Union[str, None] = '6dea55386a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_access_logs', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.alter_column('file_contents', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.alter_column('file_types', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.alter_column('files', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.alter_column('tags', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('files', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('file_types', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('file_contents', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('file_access_logs', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    # ### end Alembic commands ###
