"""empty message

Revision ID: 51303cea6f98
Revises: 401ab96e8fe8
Create Date: 2026-01-15 09:38:26.753380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51303cea6f98'
down_revision: Union[str, None] = '401ab96e8fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_access_logs', 'deleted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_comment='Время удаления',
               existing_server_default=sa.text('now()'))
    op.alter_column('file_access_logs', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.alter_column('file_contents', 'deleted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_comment='Время удаления',
               existing_server_default=sa.text('now()'))
    op.alter_column('file_contents', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.alter_column('file_types', 'deleted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_comment='Время удаления',
               existing_server_default=sa.text('now()'))
    op.alter_column('file_types', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.alter_column('files', 'deleted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_comment='Время удаления',
               existing_server_default=sa.text('now()'))
    op.alter_column('files', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.alter_column('tags', 'deleted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_comment='Время удаления',
               existing_server_default=sa.text('now()'))
    op.alter_column('tags', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('tags', 'deleted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_comment='Время удаления',
               existing_server_default=sa.text('now()'))
    op.alter_column('files', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('files', 'deleted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_comment='Время удаления',
               existing_server_default=sa.text('now()'))
    op.alter_column('file_types', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('file_types', 'deleted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_comment='Время удаления',
               existing_server_default=sa.text('now()'))
    op.alter_column('file_contents', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('file_contents', 'deleted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_comment='Время удаления',
               existing_server_default=sa.text('now()'))
    op.alter_column('file_access_logs', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('file_access_logs', 'deleted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_comment='Время удаления',
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
