"""empty message

Revision ID: 760222087138
Revises: c922ddc0a8f8
Create Date: 2026-04-20 13:39:44.171670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760222087138'
down_revision: Union[str, None] = 'c922ddc0a8f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_access_logs', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.alter_column('file_contents', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.add_column('file_types', sa.Column('extensions', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('file_types', sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('file_types', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.create_index(op.f('ix_file_types_is_default'), 'file_types', ['is_default'], unique=False)
    op.alter_column('files', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.alter_column('tags', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('files', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.drop_index(op.f('ix_file_types_is_default'), table_name='file_types')
    op.alter_column('file_types', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.drop_column('file_types', 'is_default')
    op.drop_column('file_types', 'extensions')
    op.alter_column('file_contents', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('file_access_logs', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    # ### end Alembic commands ###
