"""empty message

Revision ID: a56bbe98110b
Revises: 29b91492b87b
Create Date: 2026-09-10 09:51:48.391731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a56bbe98110b'
down_revision: Union[str, None] = '29b91492b87b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_access_logs', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.alter_column('file_contents', 'size',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Размер файла',
               existing_nullable=False)
    op.alter_column('file_contents', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.alter_column('file_types', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.alter_column('files', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.alter_column('search_query', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.alter_column('tags', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('search_query', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('files', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('file_types', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('file_contents', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('file_contents', 'size',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Размер файла',
               existing_nullable=False)
    op.alter_column('file_access_logs', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    # ### end Alembic commands ###
