"""empty message

Revision ID: aee4f954c4db
Revises: 
Create Date: 2026-01-12 13:45:24.161777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee4f954c4db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_contents',
    sa.Column('path', sa.String(), nullable=False, comment='Путь к файлу'),
    sa.Column('size', sa.Integer(), nullable=False, comment='Размер файла'),
    sa.Column('mimetype', sa.String(length=100), nullable=False, comment='Mimetype файла'),
    sa.Column('extension', sa.String(length=20), nullable=False, comment='Расширение файла'),
    sa.Column('md5_checksum', sa.String(length=32), nullable=True, comment='MD5 контрольная сумма'),
    sa.Column('sha256_checksum', sa.String(length=64), nullable=True, comment='SHA256 контрольная сумма'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время создания'),
    sa.Column('deleted', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время удаления'),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время последнего изменения'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_contents_created'), 'file_contents', ['created'], unique=False)
    op.create_index(op.f('ix_file_contents_deleted'), 'file_contents', ['deleted'], unique=False)
    op.create_index(op.f('ix_file_contents_extension'), 'file_contents', ['extension'], unique=False)
    op.create_index(op.f('ix_file_contents_mimetype'), 'file_contents', ['mimetype'], unique=False)
    op.create_index(op.f('ix_file_contents_modified'), 'file_contents', ['modified'], unique=False)
    op.create_table('file_types',
    sa.Column('name', sa.String(length=50), nullable=False, comment='Название типа файла'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время создания'),
    sa.Column('deleted', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время удаления'),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время последнего изменения'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_types_created'), 'file_types', ['created'], unique=False)
    op.create_index(op.f('ix_file_types_deleted'), 'file_types', ['deleted'], unique=False)
    op.create_index(op.f('ix_file_types_modified'), 'file_types', ['modified'], unique=False)
    op.create_table('tags',
    sa.Column('name', sa.String(), nullable=False, comment='Название тега'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='Родительский тег'),
    sa.Column('keyword', sa.Boolean(), nullable=False, comment='Принадлежность к ключевому слову'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время создания'),
    sa.Column('deleted', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время удаления'),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время последнего изменения'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_created'), 'tags', ['created'], unique=False)
    op.create_index(op.f('ix_tags_deleted'), 'tags', ['deleted'], unique=False)
    op.create_index(op.f('ix_tags_modified'), 'tags', ['modified'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=128), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('user_provider', sa.String(length=128), nullable=False, comment='Поставщик учетных данных'),
    sa.Column('username', sa.String(length=128), nullable=False, comment='Логин пользователя'),
    sa.Column('first_name', sa.String(length=128), nullable=False, comment='Имя пользователя'),
    sa.Column('last_name', sa.String(length=128), nullable=False, comment='Фамилия пользователя'),
    sa.Column('patronymic', sa.String(length=128), nullable=False, comment='Отчество пользователя'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user_provider'), 'users', ['user_provider'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('file_access_logs',
    sa.Column('file_content_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP адрес пользователя'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='User agent браузера'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время создания'),
    sa.Column('deleted', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время удаления'),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время последнего изменения'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['file_content_id'], ['file_contents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_access_logs_created'), 'file_access_logs', ['created'], unique=False)
    op.create_index(op.f('ix_file_access_logs_deleted'), 'file_access_logs', ['deleted'], unique=False)
    op.create_index(op.f('ix_file_access_logs_modified'), 'file_access_logs', ['modified'], unique=False)
    op.create_table('files',
    sa.Column('name', sa.String(), nullable=False, comment='Название файла'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание файла'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='Публичный файл'),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время создания'),
    sa.Column('deleted', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время удаления'),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время последнего изменения'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['file_contents.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['file_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_created'), 'files', ['created'], unique=False)
    op.create_index(op.f('ix_files_deleted'), 'files', ['deleted'], unique=False)
    op.create_index(op.f('ix_files_modified'), 'files', ['modified'], unique=False)
    op.create_table('file_tag_association',
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('tag_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_tag_association')
    op.drop_index(op.f('ix_files_modified'), table_name='files')
    op.drop_index(op.f('ix_files_deleted'), table_name='files')
    op.drop_index(op.f('ix_files_created'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_file_access_logs_modified'), table_name='file_access_logs')
    op.drop_index(op.f('ix_file_access_logs_deleted'), table_name='file_access_logs')
    op.drop_index(op.f('ix_file_access_logs_created'), table_name='file_access_logs')
    op.drop_table('file_access_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_provider'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_modified'), table_name='tags')
    op.drop_index(op.f('ix_tags_deleted'), table_name='tags')
    op.drop_index(op.f('ix_tags_created'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_file_types_modified'), table_name='file_types')
    op.drop_index(op.f('ix_file_types_deleted'), table_name='file_types')
    op.drop_index(op.f('ix_file_types_created'), table_name='file_types')
    op.drop_table('file_types')
    op.drop_index(op.f('ix_file_contents_modified'), table_name='file_contents')
    op.drop_index(op.f('ix_file_contents_mimetype'), table_name='file_contents')
    op.drop_index(op.f('ix_file_contents_extension'), table_name='file_contents')
    op.drop_index(op.f('ix_file_contents_deleted'), table_name='file_contents')
    op.drop_index(op.f('ix_file_contents_created'), table_name='file_contents')
    op.drop_table('file_contents')
    # ### end Alembic commands ###
