"""empty message

Revision ID: c922ddc0a8f8
Revises: 51303cea6f98
Create Date: 2026-01-16 11:35:08.518150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c922ddc0a8f8'
down_revision: Union[str, None] = '51303cea6f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_access_logs', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.alter_column('file_contents', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.add_column('file_types', sa.Column('code', sa.String(), nullable=True, comment='Уникальный код'))
    op.alter_column('file_types', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.create_index(op.f('ix_file_types_code'), 'file_types', ['code'], unique=False)
    op.alter_column('files', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    op.alter_column('tags', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('files', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.drop_index(op.f('ix_file_types_code'), table_name='file_types')
    op.alter_column('file_types', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.drop_column('file_types', 'code')
    op.alter_column('file_contents', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('file_access_logs', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    # ### end Alembic commands ###
